export const APP_CONFIG = {
  APP_NAME: 'CJ Water',
  CURRENCY: 'PHP',
  CURRENCY_SYMBOL: '₱',
  SESSION_DURATION_HOURS: 24,
  OFFLINE_QUEUE_MAX_RETRIES: 5,
  UNPAID_ORDER_ALERT_DAYS: 3,
  DEFAULT_PAGE_SIZE: 20,
} as const;
